import random
from time import sleep
import math
import time
from random import choice

#Data

no_names = (".", ",", "@", "#", "$", "%", "^", "&", "*", "()+_", "buch", "harshit", "death", "poor", "!@#$@#$@#$", "!", "~", "kuta", "nigeria", "muslim", "wrong", "dumbass", "stupid", "grel", "munic", "ass", "pussycat", "noti38uf", "bitch", "kjsakjfl")
wepick = ("cat", "dog", "perge", "nanny", "big", "perth", "canberra", "funny", "dolphin", "crater", "jam", "space", "lover", "games")
server = ("1", "2")
bots = ("Billy", "Canberra", "Servinia", "Perth", "Jacky", "Syerla", "Magil", "Chanel", "Hassen", "Danniel", "Missan", "Laylel", "Nancy", "Pelosi", "David", "Elena", "Kwan", "Smiziri (i m from south korea)", "Dang", "Matthew", "Nigjerlak", "Vhen", "Pwazki", "Layla", "Canscien", "Lola", "Rahul", "Davil", "Swetha", "Preeti", "Amanda", "Prithika", "Botania", "Swazli", "Haminia", "Jackson", "Wenleson", "Christina", "Bill", "Wilson", "Ajit", "Pakar", "Byoomkesh", "Nina", "Nita", "Mahan", "Nizamon", "Khanckqe", "Hasmuk", "Jhan", "Sarah")
messages = ("Hi", "How are you?", 'this game so boring', "peak", "import", "pond", "i spy something in my eye", "random", "let's play a game", "i have to go to the bathroom", "reopenning", "plants", "animals", "stop acting like animals", "ok boomer", "zoomer", "zoom", "i got $10 bucks", "i got $1999 in a jackpot", "''", "Aren't we friends?", "alexa play songs", "Nikita stop", "Trump keeps says 'we are testing... we are testing...'", "critics", ".,", "?<<LKXSDGKS", "stopppsssss", ":><>?", "Cannnnnnnnn", "she is my sister", "I am going to New Delhi", "coronavirus :c", "i m a bot lover", "I love this game", "Oh Ohloka", "Flutes are best", "hey no", "germany!", "ugh.... the battery is going to die", "then charge it", "begi", "stay home", "me going to bowling alley", "cars", "i m in my car", "i am traveling to Amsterdam tommorw!", "social distancing pls", "SOCIAL DISTANCING PLZZZZZZZZZZZZZZZZZZZZZZ", "PLZZZZZZZZZZZZZZZZZZZZZZ", "usa has 1 million cases :c", "very!", "mayo", "data", "Escribir cuentos dias??", "Non", "ugh---", "Schools out", "hey, {} say something:", "hiiiiiiiiii", "lol", "funnnnn", "i like chicken", "what's your favorite food", "same", "ugh", "bye", "boring", "don't be shy", "any song recommendations", "girls like you song", "mama", "no", "tinyurl.com/python-coding-class/", "no no", "bhoom", "ston", "houston", "geuch98fuy9", "h9ugr98ygeh9u fwe>spnn", "spammer", "wanna", "hui", "chingchong", "me bored what should we do Sarah", "sho", "stop", "no lol", "yes lol", "$%#$%#$%", "aye me nin9 9d", "add me on snapchat plzzZ")

#Code Starts here:
serve = random.choice(server)
if serve == "1":
    print("meet.Online Friends")
    sleep(2)
    name = input("What is your name: ").lower()
    if name in no_names:
        wepick = random.choice(name)
    else:
        sleep(1)
    #Pick the Bots
        
    c1 = random.choice(bots)
    c2 = random.choice(bots)
    c3 = random.choice(bots)
    c4 = random.choice(bots)
    c5 = random.choice(bots)
    c6 = random.choice(bots)
    c7 = random.choice(bots)
    c8 = random.choice(bots)
    c9 = random.choice(bots)
    c10 = random.choice(bots)
    c11 = random.choice(bots)
    c12 = random.choice(bots)
    c13 = random.choice(bots)
    c14 = random.choice(bots)
    c19 = choice(bots)
    c20 = choice(bots)

    #Show the bots
    
    print("Welcome to server 1, {}".format(name))
    input("What would you like to say to the chat before joining: ")
    print("Thanks")

    sleep(8)

    print("                               ")
    sleep(2)

    print("You joined")
    print(c3, "joined")
    print(c5, "says", c1, c2, c3, c4, "Hi")
    print(c5, ": Hey guys, I am from South Korea!")
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")




    #more

    
    c12 = choice(bots)

    print(c12, "has joined")

    c13 = choice(bots)

    print(c13, "has joined")

    c15 = choice(bots)
    print(c13, "has joined")

    print(c13, "has left")

    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    c13 = choice(bots)

    print(c13, "has joined")
    sleep(3)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")
    
    print(c3, "joined")
    print(c5, "says", c1, c2, c3, c4, "Hi")
    print(c5, ": Hey guys, I am from South Korea!")
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    input("Type something: ")
    print("Sent.")
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    input("Type something: ")
    print("Sent.")
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")




    #more


    c12 = choice(bots)

    print(c12, "has joined")

    c13 = choice(bots)

    print(c13, "has joined")

    c15 = choice(bots)
    print(c13, "has joined")

    print(c13, "has left")

    ran = random.choice(messages)
    print(c13, ":", ran)
    input("Type something: ")
    print("Sent.")
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    input("Type something: ")
    print("Sent.")
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    input("Type something: ")
    print("Sent.")
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    c13 = choice(bots)

    print(c13, "has joined")
    sleep(3)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")
    
    print(c3, "joined")
    print(c5, "says", c1, c2, c3, c4, "Hi")
    print(c5, ": Hey guys, I am from South Korea!")
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")

   


    while True:
        #more


        c12 = choice(bots)

        print(c12, "has joined")

        c13 = choice(bots)

        print(c13, "has joined")

        c15 = choice(bots)
        print(c13, "has joined")

        print(c13, "has left")

        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(3)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(3)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(11)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(3)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c7, ":", ra)
        sleep(1)
        sleep(1)
        sleep(1)
        c13 = choice(bots)

        print(c13, "has joined")
        sleep(3)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        ra = random.choice(messages)
        print(c7, ":", ra)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        sleep(1)
        input("Type something: ")
        input("Type something: ")


        ran = random.choice(messages)
        print(c1, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c3, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c4, ":", ra)
        ra = random.choice(messages)
        sleep(1)
        print("Player", c12, "left")
        
        
        print(c3, "joined")
        print(c5, "says", c1, c2, c3, c4, "Hi")
        print(c5, ": Hey guys, I am from South Korea!")
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(3)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(3)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(11)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        input("Type something: ")
        print("Sent.")
        sleep(3)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c7, ":", ra)
        sleep(1)
        sleep(1)
        sleep(1)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        input("Type something: ")
        print("Sent.")
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        ra = random.choice(messages)
        print(c7, ":", ra)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        sleep(1)
        input("Type something: ")
        input("Type something: ")


        ran = random.choice(messages)
        print(c1, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c3, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c4, ":", ra)
        ra = random.choice(messages)
        sleep(1)
        print("Player", c12, "left")




        #more


        c12 = choice(bots)

        print(c12, "has joined")

        c13 = choice(bots)

        print(c13, "has joined")

        c15 = choice(bots)
        print(c13, "has joined")

        print(c13, "has left")

        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(3)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(3)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(11)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(3)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c7, ":", ra)
        sleep(1)
        sleep(1)
        sleep(1)
        c13 = choice(bots)

        print(c13, "has joined")
        sleep(3)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        ra = random.choice(messages)
        print(c7, ":", ra)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        sleep(1)
        input("Type something: ")
        input("Type something: ")


        ran = random.choice(messages)
        print(c1, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c3, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c4, ":", ra)
        ra = random.choice(messages)
        sleep(1)
        print("Player", c12, "left")

        input("something: ")
        input(":  ")
        input("something: ")
        input(":  ")

        ran = random.choice(messages)
        print(c1, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c3, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c4, ":", ra)
        ra = random.choice(messages)
        sleep(1)
        print("Player", c12, "left")
        input("something: ")
        input(":  ")
        input("something: ")
        input(":  ")

        hey = input("Would you like to leave this server?: Y/N").lower()

        if hey == "y":
            print("bye")
            sleep(3)
            break
        else:
            print("Ok")
            sleep(1)
        
elif serve == "2":
    print("Server2")
    print("meet.Online Friends")
    sleep(2)
    name = input("What is your name: ").lower()
    if name in no_names:
        wepick = random.choice(name)
    else:
        sleep(1)
    #Pick the Bots
        
    c1 = random.choice(bots)
    c2 = random.choice(bots)
    c3 = random.choice(bots)
    c4 = random.choice(bots)
    c5 = random.choice(bots)
    c6 = random.choice(bots)
    c7 = random.choice(bots)
    c8 = random.choice(bots)
    c9 = random.choice(bots)
    c10 = random.choice(bots)
    c11 = random.choice(bots)
    c12 = random.choice(bots)
    c13 = random.choice(bots)

    #Show the bots
    
    print("Welcome to server 1, {}".format(name))
    input("What would you like to say to the chat before joining: ")
    print("Thanks")

    sleep(8)

    print("                               ")
    sleep(2)

    print("You joined")
    print(c3, "joined")
    print(c5, "says", c1, c2, c3, c4, "Hi")
    print(c5, ": Hey guys, I am from South Korea!")
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")




    #more

    
    c12 = choice(bots)

    print(c12, "has joined")

    c13 = choice(bots)

    print(c13, "has joined")

    c15 = choice(bots)
    print(c13, "has joined")

    print(c13, "has left")

    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    c13 = choice(bots)

    print(c13, "has joined")
    sleep(3)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")
    
    print(c3, "joined")
    print(c5, "says", c1, c2, c3, c4, "Hi")
    print(c5, ": Hey guys, I am from South Korea!")
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    input("Type something: ")
    print("Sent.")
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    input("Type something: ")
    print("Sent.")
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")




    #more


    c12 = choice(bots)

    print(c12, "has joined")

    c13 = choice(bots)

    print(c13, "has joined")

    c15 = choice(bots)
    print(c13, "has joined")

    print(c13, "has left")

    ran = random.choice(messages)
    print(c13, ":", ran)
    input("Type something: ")
    print("Sent.")
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    input("Type something: ")
    print("Sent.")
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    input("Type something: ")
    print("Sent.")
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    c13 = choice(bots)

    print(c13, "has joined")
    sleep(3)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")
    
    print(c3, "joined")
    print(c5, "says", c1, c2, c3, c4, "Hi")
    print(c5, ": Hey guys, I am from South Korea!")
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(3)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(3)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(11)
    ra = random.choice(messages)
    print(c1, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(3)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c7, ":", ra)
    sleep(1)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c13, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c12, ":", ra)
    sleep(1)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c1, ":", ra)
    ra = random.choice(messages)
    print(c9, ":", ra)
    sleep(1)
    ran = random.choice(messages)
    print(c5, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c6, ":", ra)
    ra = random.choice(messages)
    print(c7, ":", ra)
    ra = random.choice(messages)
    print(c8, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c11, ":", ra)
    sleep(1)
    sleep(1)
    input("Type something: ")
    input("Type something: ")


    ran = random.choice(messages)
    print(c1, ":", ran)
    sleep(1)
    ra = random.choice(messages)
    print(c2, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c3, ":", ra)
    sleep(1)
    ra = random.choice(messages)
    print(c4, ":", ra)
    ra = random.choice(messages)
    sleep(1)
    print("Player", c12, "left")

   


    while True:
        #more


        c12 = choice(bots)

        print(c12, "has joined")

        c13 = choice(bots)

        print(c13, "has joined")

        c15 = choice(bots)
        print(c13, "has joined")

        print(c13, "has left")

        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(3)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(3)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(11)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(3)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c7, ":", ra)
        sleep(1)
        sleep(1)
        sleep(1)
        c13 = choice(bots)

        print(c13, "has joined")
        sleep(3)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        ra = random.choice(messages)
        print(c7, ":", ra)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        sleep(1)
        input("Type something: ")
        input("Type something: ")


        ran = random.choice(messages)
        print(c1, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c3, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c4, ":", ra)
        ra = random.choice(messages)
        sleep(1)
        print("Player", c12, "left")
        
        
        print(c3, "joined")
        print(c5, "says", c1, c2, c3, c4, "Hi")
        print(c5, ": Hey guys, I am from South Korea!")
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(3)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(3)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(11)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        input("Type something: ")
        print("Sent.")
        sleep(3)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c7, ":", ra)
        sleep(1)
        sleep(1)
        sleep(1)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        input("Type something: ")
        print("Sent.")
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        ra = random.choice(messages)
        print(c7, ":", ra)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        sleep(1)
        input("Type something: ")
        input("Type something: ")


        ran = random.choice(messages)
        print(c1, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c3, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c4, ":", ra)
        ra = random.choice(messages)
        sleep(1)
        print("Player", c12, "left")




        #more


        c12 = choice(bots)

        print(c12, "has joined")

        c13 = choice(bots)

        print(c13, "has joined")

        c15 = choice(bots)
        print(c13, "has joined")

        print(c13, "has left")

        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(3)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(3)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(11)
        ra = random.choice(messages)
        print(c1, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(3)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c7, ":", ra)
        sleep(1)
        sleep(1)
        sleep(1)
        c13 = choice(bots)

        print(c13, "has joined")
        sleep(3)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c13, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c12, ":", ra)
        sleep(1)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c1, ":", ra)
        ra = random.choice(messages)
        print(c9, ":", ra)
        sleep(1)
        ran = random.choice(messages)
        print(c5, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c6, ":", ra)
        ra = random.choice(messages)
        print(c7, ":", ra)
        ra = random.choice(messages)
        print(c8, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c11, ":", ra)
        sleep(1)
        sleep(1)
        input("Type something: ")
        input("Type something: ")


        ran = random.choice(messages)
        print(c1, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c3, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c4, ":", ra)
        ra = random.choice(messages)
        sleep(1)
        print("Player", c12, "left")

        input("something: ")
        input(":  ")
        input("something: ")
        input(":  ")

        ran = random.choice(messages)
        print(c1, ":", ran)
        sleep(1)
        ra = random.choice(messages)
        print(c2, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c3, ":", ra)
        sleep(1)
        ra = random.choice(messages)
        print(c4, ":", ra)
        ra = random.choice(messages)
        sleep(1)
        print("Player", c12, "left")
        input("something: ")
        input(":  ")
        input("something: ")
        input(":  ")

        hey = input("Would you like to leave this server?: Y/N").lower()

        if hey == "y":
            print("bye")
            sleep(3)
            break
        else:
            print("Ok")
            sleep(1)
            ra = random.choice(messages)
            print(c14, ":", ra)
            ra = random.choice(messages)
            print(c19, ":", ra)
            ra = random.choice(messages)
            print(c20, ":", ra)
            sleep(1)
            ra = random.choice(messages)
            print(c16, ":", ra)
        
## Both were the same
